apiVersion: v1
kind: Secret
metadata:
  name: campaign-manager-secret
  labels:
    app.kubernetes.io/name: campaign-manager-secret
type: Opaque
data:
  # Base64 encoded values
  postgres_password: cG9zdGdyZXM=
