apiVersion: v1
kind: Service
metadata:
  name: campaign-manager-api-service
  labels:
    app.kubernetes.io/name: campaign-manager-api-service
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: campaign-manager-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
    name: http
